import type { BaseName, GeneData, GeneLocation } from './types';

// ── DATA ────────────────────────────────────────────────────────────────────

export const BASES = ['A', 'T', 'C', 'G'] as const;
export const BASE_LABEL: Record<BaseName, string> = {
  A: 'Yellow',
  T: 'Red',
  C: 'Blue',
  G: 'Green',
};
export const BASE_IDX: Record<BaseName, number> = { A: 0, T: 1, C: 2, G: 3 };

export const CAT_COLOR: Record<string, string> = {
  Body: '#f97316',
  Legs: '#a78bfa',
  Arms: '#fb7185',
  Neck: '#34d399',
  Tail: '#f59e0b',
  Feet: '#38bdf8',
  Head: '#e879f9',
  Face: '#818cf8',
  Mouth: '#fb923c',
  Antlers: '#86efac',
  Hat: '#fbbf24',
  Color: '#6ee7b7',
  Pattern: '#67e8f9',
  Locomotion: '#f472b6',
  Behavior: '#94a3b8',
  Signals: '#c084fc',
};

export const GENES = {
  SIZE: {
    maxValue: 95,
    scale: 100,
    alleleValues: [100, 50, 35, 75],
    category: 'Body',
  },
  ASPECT: {
    maxValue: 95,
    scale: 100,
    alleleValues: [200, 310, 150, 250],
    category: 'Body',
  },
  SKINNY: {
    maxValue: 100,
    scale: 100,
    alleleValues: [100, 200, 100, 75],
    category: 'Body',
  },
  BONES: {
    maxValue: 95,
    scale: 100,
    alleleValues: [0, -14, 14, 0],
    category: 'Body',
  },
  BONES2: {
    maxValue: 60,
    scale: 100,
    alleleValues: [0, 16, -16, 0],
    category: 'Body',
  },
  CHEST_BIG: {
    maxValue: 100,
    scale: 100,
    alleleValues: [104, 102, 108, 102],
    category: 'Body',
  },
  CHEST_SMALL: {
    maxValue: 100,
    scale: 100,
    alleleValues: [95, 100, 90, 95],
    category: 'Body',
  },
  GIANT_DWARF: {
    maxValue: 100,
    scale: 100,
    alleleValues: [100, 66, 133, 100],
    category: 'Body',
  },
  MUSCLE_USE: {
    maxValue: 100,
    scale: 100,
    alleleValues: [100, 50, 80, 100],
    category: 'Body',
  },
  GUT: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 25, 45, 0],
    category: 'Body',
  },
  GUT_IS_UDDER: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 2],
    category: 'Body',
  },
  DERRIERE: {
    maxValue: 85,
    scale: 100,
    alleleValues: [0, 40, 70, 10],
    category: 'Body',
  },
  OSTODERM: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 1, 2],
    category: 'Body',
  },
  OSTO_SIZE: {
    maxValue: 100,
    scale: 100,
    alleleValues: [30, 15, 45, 30],
    category: 'Body',
  },
  SPLAY: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 10, -5, 45],
    category: 'Legs',
  },
  LEG_IN: {
    maxValue: 50,
    scale: 100,
    alleleValues: [0, 18, 6, 0],
    category: 'Legs',
  },
  LEG_IN2: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 13, 0, 1],
    category: 'Legs',
  },
  LEG_TAG: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 2, 4, 3],
    category: 'Legs',
  },
  LEG_TYPE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 2, 0, 1],
    category: 'Legs',
  },
  LEG_LENGTH: {
    maxValue: 90,
    scale: 100,
    alleleValues: [80, 50, 120, 100],
    category: 'Legs',
  },
  LEG_STRETCH: {
    maxValue: 60,
    scale: 100,
    alleleValues: [0, 14, -14, 0],
    category: 'Legs',
  },
  LEG_STRETCH2: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, -16, 16, 0],
    category: 'Legs',
  },
  LEG_STRENGTH: {
    maxValue: 60,
    scale: 100,
    alleleValues: [95, 120, 80, 104],
    category: 'Legs',
  },
  LEG_HAS_FOOT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 1, 0, 0],
    category: 'Legs',
  },
  LEG_JOINT_TYPE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 0],
    category: 'Legs',
  },
  LEG_FLEXIBILITY: {
    maxValue: 80,
    scale: 1,
    alleleValues: [30, 20, 40, 50],
    category: 'Legs',
  },
  LEG_FLEX_BIAS: {
    maxValue: 100,
    scale: 1,
    alleleValues: [15, 20, 10, -10],
    category: 'Legs',
  },
  LEG_THRUST_BACK: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 2],
    category: 'Legs',
  },
  LEG_IS_CIRCLE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Legs',
  },
  LEG_COUNT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 1, 2, 7],
    category: 'Legs',
  },
  LEG_SKEW: {
    maxValue: 60,
    scale: 100,
    alleleValues: [0, 24, -16, 0],
    category: 'Legs',
  },
  LEG_PENCIL: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 10, 0, 0],
    category: 'Legs',
  },
  LEG_AND_ARM_LIMP: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 0, 0, 1],
    category: 'Legs',
  },
  HAS_KNEE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Legs',
  },
  KNEE_MIN: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, -90, -15, 0],
    category: 'Legs',
  },
  KNEE_MAX: {
    maxValue: 100,
    scale: 1,
    alleleValues: [20, 90, 45, 20],
    category: 'Legs',
  },
  STIFF_JOINTS: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 18, 50, 0],
    category: 'Legs',
  },
  QUADRUPED: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 1, 0],
    category: 'Locomotion',
  },
  BIPED: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 1],
    category: 'Locomotion',
  },
  SPEED_FACTOR: {
    maxValue: 75,
    scale: 100,
    alleleValues: [100, 30, 50, 133],
    category: 'Locomotion',
  },
  BREAK_FORCE: {
    maxValue: 100,
    scale: 10,
    alleleValues: [0, 50, 0, 30],
    category: 'Locomotion',
  },
  SPINAL_LOCO: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 2],
    category: 'Locomotion',
  },
  LOCO_SYNC: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Locomotion',
  },
  RAMPAGE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 0, 0, 1],
    category: 'Locomotion',
  },
  BRAIN_SPASTIC: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 0],
    category: 'Locomotion',
  },
  NARCOLEPSY: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 0, 1, 0],
    category: 'Locomotion',
  },
  ARM_TAG: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 2, 4, 3],
    category: 'Arms',
  },
  ARM_TYPE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 2, 0, 0],
    category: 'Arms',
  },
  ARM_LENGTH: {
    maxValue: 90,
    scale: 100,
    alleleValues: [80, 50, 120, 25],
    category: 'Arms',
  },
  ARM_STRETCH: {
    maxValue: 60,
    scale: 100,
    alleleValues: [0, 14, -14, 0],
    category: 'Arms',
  },
  ARM_STRETCH2: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, -16, 16, 0],
    category: 'Arms',
  },
  ARM_STRENGTH: {
    maxValue: 60,
    scale: 100,
    alleleValues: [95, 120, 80, 104],
    category: 'Arms',
  },
  ARM_HAS_HAND: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 1, 0],
    category: 'Arms',
  },
  ARM_JOINT_TYPE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 0],
    category: 'Arms',
  },
  ARM_FLEXIBILITY: {
    maxValue: 100,
    scale: 1,
    alleleValues: [30, 20, 40, 30],
    category: 'Arms',
  },
  ARM_FLEX_BIAS: {
    maxValue: 100,
    scale: 1,
    alleleValues: [15, 20, 10, 0],
    category: 'Arms',
  },
  ARM_FORWARD: {
    maxValue: 100,
    scale: 1,
    alleleValues: [-20, 0, 60, 40],
    category: 'Arms',
  },
  ARM_SKEW: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 20, -20, 0],
    category: 'Arms',
  },
  ARM_NODE_SCALE: {
    maxValue: 50,
    scale: 100,
    alleleValues: [100, 70, 130, 100],
    category: 'Arms',
  },
  HAS_ELBOW: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Arms',
  },
  ELBOW_RANGE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [30, 90, 10, 30],
    category: 'Arms',
  },
  UPARM_TAG: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 2, 1, 4],
    category: 'Arms',
  },
  UPARM_Y: {
    maxValue: 80,
    scale: 100,
    alleleValues: [30, 10, 30, 50],
    category: 'Arms',
  },
  UPARM_ANGLE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 30, -30, -45],
    category: 'Arms',
  },
  UPARM_GOOFY: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 3],
    category: 'Arms',
  },
  NECK_TAG: {
    maxValue: 100,
    scale: 1,
    alleleValues: [4, 3, 1, 2],
    category: 'Neck',
  },
  NECK_TYPE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 1, 2, 0],
    category: 'Neck',
  },
  NECK_LENGTH: {
    maxValue: 90,
    scale: 100,
    alleleValues: [60, 70, 90, 30],
    category: 'Neck',
  },
  NECK_GIRAFFE: {
    maxValue: 90,
    scale: 100,
    alleleValues: [110, 0, 85, 120],
    category: 'Neck',
  },
  NECK_THICKNESS: {
    maxValue: 60,
    scale: 100,
    alleleValues: [95, 110, 120, 80],
    category: 'Neck',
  },
  NECK_ANGLE: {
    maxValue: 90,
    scale: 1,
    alleleValues: [45, 30, 60, 75],
    category: 'Neck',
  },
  NECK_COCK: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 30, 20, -25],
    category: 'Neck',
  },
  NECK_SIZE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 0, 0, 0],
    category: 'Neck',
  },
  NECK_JOINT_TYPE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 2, 0],
    category: 'Neck',
  },
  NECK_FLEXIBILITY: {
    maxValue: 100,
    scale: 1,
    alleleValues: [23, 10, 40, 0],
    category: 'Neck',
  },
  NECK_FLEX_BIAS: {
    maxValue: 100,
    scale: 1,
    alleleValues: [-8, 0, -25, 30],
    category: 'Neck',
  },
  NECK_SLOUCH: {
    maxValue: 60,
    scale: 100,
    alleleValues: [0, 50, 20, 0],
    category: 'Neck',
  },
  NECK_ONTOP: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 50, 70, 20],
    category: 'Neck',
  },
  NECK_STIFF: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 1],
    category: 'Neck',
  },
  NECK_SPEED: {
    maxValue: 100,
    scale: 10,
    alleleValues: [60, 25, 50, 10],
    category: 'Neck',
  },
  TAIL_TAG: {
    maxValue: 100,
    scale: 1,
    alleleValues: [3, 4, 2, 1],
    category: 'Tail',
  },
  TAIL_EXISTS: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 1, 2],
    category: 'Tail',
  },
  TAIL_SIZE: {
    maxValue: 60,
    scale: 100,
    alleleValues: [100, 80, 120, 140],
    category: 'Tail',
  },
  TAIL_SHORT: {
    maxValue: 100,
    scale: 100,
    alleleValues: [100, 50, 35, 100],
    category: 'Tail',
  },
  TAIL_ASPECT: {
    maxValue: 90,
    scale: 100,
    alleleValues: [20, 10, 30, 20],
    category: 'Tail',
  },
  TAIL_ANGLE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [45, 90, 135, 60],
    category: 'Tail',
  },
  TAIL_JOINT_TYPE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Tail',
  },
  TAIL_STIFF: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 1],
    category: 'Tail',
  },
  TAIL_SPEED: {
    maxValue: 100,
    scale: 10,
    alleleValues: [60, 200, 60, 0],
    category: 'Tail',
  },
  TAIL_FLEXIBILITY: {
    maxValue: 100,
    scale: 1,
    alleleValues: [135, 90, 45, 15],
    category: 'Tail',
  },
  TAIL_SHAPE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [2, 1, 5, 6],
    category: 'Tail',
  },
  TAIL_BOTTOM: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Tail',
  },
  TAIL_SEGMENTS: {
    maxValue: 100,
    scale: 1,
    alleleValues: [3, 0, 3, 5],
    category: 'Tail',
  },
  TAIL_WAG: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 0, 0],
    category: 'Tail',
  },
  TAIL_ALT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 0],
    category: 'Tail',
  },
  HAS_FOOT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 1, 0],
    category: 'Feet',
  },
  FOOT_SIZE: {
    maxValue: 60,
    scale: 100,
    alleleValues: [0, 20, 12, 30],
    category: 'Feet',
  },
  FOOT_CLOWN: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 30, 0, 0],
    category: 'Feet',
  },
  FOOT_THICKNESS: {
    maxValue: 80,
    scale: 100,
    alleleValues: [20, 15, 30, 7],
    category: 'Feet',
  },
  FOOT_TOE: {
    maxValue: 100,
    scale: 100,
    alleleValues: [100, 0, 50, 100],
    category: 'Feet',
  },
  FOOT_IS_CIRCLE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Feet',
  },
  FOOT_BACKWARDS: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 2],
    category: 'Feet',
  },
  FOOT_IS_HOOF: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 1],
    category: 'Feet',
  },
  HAS_HAND: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 1],
    category: 'Feet',
  },
  HAND_WIDTH: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 7, 20, 0],
    category: 'Feet',
  },
  HAND_LENGTH: {
    maxValue: 90,
    scale: 100,
    alleleValues: [20, 30, 15, 20],
    category: 'Feet',
  },
  HAND_FINGER: {
    maxValue: 80,
    scale: 100,
    alleleValues: [0, 100, 0, 50],
    category: 'Feet',
  },
  SKIN_HANDS: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 2],
    category: 'Feet',
  },
  HEAD_SIZE: {
    maxValue: 95,
    scale: 100,
    alleleValues: [100, 50, 133, 75],
    category: 'Head',
  },
  HEAD_THICK_SKULL: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 20, 0, 0],
    category: 'Head',
  },
  HEAD_X_GROWTH: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 5, 10, -5],
    category: 'Head',
  },
  HEAD_Y_GROWTH: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 5, -5, 0],
    category: 'Head',
  },
  HEAD_ASPECT: {
    maxValue: 85,
    scale: 100,
    alleleValues: [200, 175, 250, 300],
    category: 'Head',
  },
  HEAD_SQUARE: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 150, 100, 0],
    category: 'Head',
  },
  HEAD_HAS_BACK: {
    maxValue: 100,
    scale: 1,
    alleleValues: [11, 0, 0, 1],
    category: 'Head',
  },
  HEAD_GIANT: {
    maxValue: 90,
    scale: 100,
    alleleValues: [100, 200, 180, 100],
    category: 'Head',
  },
  HEAD_SHRUNK: {
    maxValue: 90,
    scale: 100,
    alleleValues: [100, 70, 50, 100],
    category: 'Head',
  },
  HEAD_JOINTED: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Head',
  },
  HEAD_CHIMERA: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Head',
  },
  SKIN_HEAD: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 2],
    category: 'Head',
  },
  EYE_STYLE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 2, 1, 0],
    category: 'Face',
  },
  BUGEYE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 2],
    category: 'Face',
  },
  EYEBOX_X: {
    maxValue: 90,
    scale: 100,
    alleleValues: [33, 0, 50, 15],
    category: 'Face',
  },
  EYEBOX_Y: {
    maxValue: 100,
    scale: 100,
    alleleValues: [-100, 0, -50, -25],
    category: 'Face',
  },
  EYEBOX_SIZE: {
    maxValue: 60,
    scale: 100,
    alleleValues: [25, 15, 33, 50],
    category: 'Face',
  },
  EYE_SIZE: {
    maxValue: 100,
    scale: 100,
    alleleValues: [50, 75, 125, 50],
    category: 'Face',
  },
  PUPIL_SIZE: {
    maxValue: 100,
    scale: 100,
    alleleValues: [66, 80, 40, 40],
    category: 'Face',
  },
  HAS_PUPIL: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 0, 0],
    category: 'Face',
  },
  BROW_SIZE: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 150, 125, 0],
    category: 'Face',
  },
  BROW_SLANT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, -15, 15, 0],
    category: 'Face',
  },
  EYE_HUE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [36, 237, 153, 198],
    category: 'Face',
  },
  EAR_STYLE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 2, 0, 0],
    category: 'Face',
  },
  EAR_SHAPE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [2, 1, 4, 2],
    category: 'Face',
  },
  EAR_FLOP: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 30, 60, 200],
    category: 'Face',
  },
  EAR_X: {
    maxValue: 90,
    scale: 100,
    alleleValues: [0, 100, 50, 0],
    category: 'Face',
  },
  EAR_SIZE: {
    maxValue: 70,
    scale: 100,
    alleleValues: [20, 30, 10, 40],
    category: 'Face',
  },
  EAR_ASPECT: {
    maxValue: 100,
    scale: 100,
    alleleValues: [100, 250, 300, 100],
    category: 'Face',
  },
  EAR_SLANT: {
    maxValue: 70,
    scale: 100,
    alleleValues: [0, 100, 50, -33],
    category: 'Face',
  },
  EAR_INTERIOR: {
    maxValue: 100,
    scale: 100,
    alleleValues: [5, 0, 0, 0],
    category: 'Face',
  },
  EAR_COMP: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 0, 2, 1],
    category: 'Face',
  },
  COON_EYE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 0],
    category: 'Face',
  },
  TEETH_SHAPE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 3],
    category: 'Mouth',
  },
  HAS_MOUTH: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 1, 0, 1],
    category: 'Mouth',
  },
  MOUTH_Y: {
    maxValue: 80,
    scale: 100,
    alleleValues: [70, 84, 50, 100],
    category: 'Mouth',
  },
  MOUTH_SIZE: {
    maxValue: 70,
    scale: 100,
    alleleValues: [20, 30, 10, 40],
    category: 'Mouth',
  },
  JAW: {
    maxValue: 50,
    scale: 100,
    alleleValues: [0, 15, -8, -13],
    category: 'Mouth',
  },
  TEETH_UPPER: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 0, 0],
    category: 'Mouth',
  },
  TEETH_UPPER2: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 0, 0],
    category: 'Mouth',
  },
  TONGUE: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 40, 60, 0],
    category: 'Mouth',
  },
  TONGUE_SEGS: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 0],
    category: 'Mouth',
  },
  NOSE_STYLE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 2, 3, 0],
    category: 'Mouth',
  },
  NOSE_INNY: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Mouth',
  },
  NOSE_Y: {
    maxValue: 90,
    scale: 100,
    alleleValues: [0, 100, 50, 0],
    category: 'Mouth',
  },
  NOSE_SIZE: {
    maxValue: 70,
    scale: 100,
    alleleValues: [10, 5, 20, 100],
    category: 'Mouth',
  },
  NOSE_INTERIOR: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 100, 50, 0],
    category: 'Mouth',
  },
  NOSE_HUE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 3],
    category: 'Mouth',
  },
  FLU_IMMUNITY: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 0, 0, 1],
    category: 'Mouth',
  },
  HAS_ANTLERS: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 1, 1],
    category: 'Antlers',
  },
  ANTLER_X: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 2, 1],
    category: 'Antlers',
  },
  ANTLER_W: {
    maxValue: 100,
    scale: 100,
    alleleValues: [15, 12, 8, 12],
    category: 'Antlers',
  },
  ANTLER_H: {
    maxValue: 80,
    scale: 100,
    alleleValues: [65, 45, 100, 25],
    category: 'Antlers',
  },
  ANTLER_TAPER: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 100, 50, 100],
    category: 'Antlers',
  },
  ANTLER_POM: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 150, 200, 100],
    category: 'Antlers',
  },
  ANTLER_COLOR: {
    maxValue: 100,
    scale: 1,
    alleleValues: [2, 8, 1, 3],
    category: 'Antlers',
  },
  POM_COLOR: {
    maxValue: 100,
    scale: 1,
    alleleValues: [2, 0, 1, 17],
    category: 'Antlers',
  },
  POM_USECOLOR: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 0, 0],
    category: 'Antlers',
  },
  ANTLER_REC: {
    maxValue: 100,
    scale: 1,
    alleleValues: [2, 1, 3, 0],
    category: 'Antlers',
  },
  ANTLER_REC2: {
    maxValue: 100,
    scale: 1,
    alleleValues: [2, 1, 3, 0],
    category: 'Antlers',
  },
  ANTLER_FLIP: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 0, 0],
    category: 'Antlers',
  },
  ANTLER_MOD: {
    maxValue: 100,
    scale: 1,
    alleleValues: [3, 2, 1, 3],
    category: 'Antlers',
  },
  ANTLER_SCALEH: {
    maxValue: 80,
    scale: 100,
    alleleValues: [100, 75, 40, 100],
    category: 'Antlers',
  },
  ANTLER_SCALEW: {
    maxValue: 100,
    scale: 100,
    alleleValues: [100, 75, 50, 100],
    category: 'Antlers',
  },
  ANTLER_ANGLE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [45, -45, -25, 25],
    category: 'Antlers',
  },
  ANTLER_ANGLE2: {
    maxValue: 100,
    scale: 1,
    alleleValues: [45, -45, 90, -90],
    category: 'Antlers',
  },
  ANTLER_ANGLE_RAND: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 5, 45, 15],
    category: 'Antlers',
  },
  ANTLER_T1: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 100, 40, 25],
    category: 'Antlers',
  },
  ANTLER_T2: {
    maxValue: 100,
    scale: 100,
    alleleValues: [100, 40, 0, 25],
    category: 'Antlers',
  },
  HAT_EXISTS: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 0, 0],
    category: 'Hat',
  },
  HAT_SIZE: {
    maxValue: 85,
    scale: 100,
    alleleValues: [60, 40, 100, 20],
    category: 'Hat',
  },
  HAT_RAKE: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 25, -15, 0],
    category: 'Hat',
  },
  HAT_ASPECT: {
    maxValue: 85,
    scale: 100,
    alleleValues: [100, 300, 200, 100],
    category: 'Hat',
  },
  HAT_TAPER: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 100, 50, 0],
    category: 'Hat',
  },
  HAT_POM: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 25, 50, 0],
    category: 'Hat',
  },
  HAT_POM_IS_LID: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Hat',
  },
  HAT_CLONE: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 33, 66, 0],
    category: 'Hat',
  },
  HAT_BACK_SCALE: {
    maxValue: 100,
    scale: 100,
    alleleValues: [100, 0, 60, 100],
    category: 'Hat',
  },
  HAT_FRONT_SCALE: {
    maxValue: 100,
    scale: 100,
    alleleValues: [100, 0, 60, 100],
    category: 'Hat',
  },
  HAT_BACK_ANGLE: {
    maxValue: 75,
    scale: 1,
    alleleValues: [45, 90, 120, 60],
    category: 'Hat',
  },
  HAT_FRONT_ANGLE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [-45, -90, -120, -60],
    category: 'Hat',
  },
  HAT_ANGLE_RAND: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 15, 45, 15],
    category: 'Hat',
  },
  HAT_FLIP: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Hat',
  },
  HAT_T: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 100, 40, 0],
    category: 'Hat',
  },
  BASE_BROWN: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 0],
    category: 'Color',
  },
  BASE_BLACK: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 1],
    category: 'Color',
  },
  BASE_RED: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 3],
    category: 'Color',
  },
  BASE_GREEN: {
    maxValue: 70,
    scale: 1,
    alleleValues: [0, 1, 2, 3],
    category: 'Color',
  },
  GREEN_KNOCKOUT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Color',
  },
  BASE_CREAM: {
    maxValue: 50,
    scale: 100,
    alleleValues: [0, 100, 0, 0],
    category: 'Color',
  },
  ALT_BLUE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 3],
    category: 'Color',
  },
  SPOT_YELLOW: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 1],
    category: 'Color',
  },
  SKIN_HUE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 3],
    category: 'Color',
  },
  SKIN_HUE2: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 3],
    category: 'Color',
  },
  SWAP_BASE_SPOT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 1],
    category: 'Color',
  },
  SWAP_ALT_SPOT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 1],
    category: 'Color',
  },
  WHITE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 0, 0],
    category: 'Color',
  },
  WHITE_IS_LETHAL: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Color',
  },
  HOOF_COLOR: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 0],
    category: 'Color',
  },
  AGOUTI: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 0, 0, 1],
    category: 'Color',
  },
  BELLY_ALT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 2, 1],
    category: 'Color',
  },
  PAT_SPLIT: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 100, 65, 0],
    category: 'Pattern',
  },
  PAT_BELLY: {
    maxValue: 100,
    scale: 100,
    alleleValues: [100, 50, 33, 75],
    category: 'Pattern',
  },
  PAT_STRIPE: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 90, 51, 0],
    category: 'Pattern',
  },
  PAT_SPOT: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 90, 51, 0],
    category: 'Pattern',
  },
  PAT_PERLIN: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 100, 60, 0],
    category: 'Pattern',
  },
  PAT_PERLIN2: {
    maxValue: 100,
    scale: 100,
    alleleValues: [0, 100, 60, 0],
    category: 'Pattern',
  },
  PAT_PERLIN_SIZE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [8, 2, 4, 4],
    category: 'Pattern',
  },
  HIGH_INTELLECT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 1],
    category: 'Behavior',
  },
  OMNIVORE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 0],
    category: 'Behavior',
  },
  LITTER_SIZE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 2, 3, 5],
    category: 'Behavior',
  },
  OLD_AGE: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 0, -1, 2],
    category: 'Behavior',
  },
  LIMP: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 0, 2],
    category: 'Behavior',
  },
  L_LEG_SIGNAL: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 1, 1, 2],
    category: 'Signals',
  },
  L_LEG_FTOB_REACT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 2, 1, 3],
    category: 'Signals',
  },
  L_LEG_FTOB_EVENT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [3, 1, 2, 4],
    category: 'Signals',
  },
  L_LEG_BTOF_REACT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [2, 1, 2, 3],
    category: 'Signals',
  },
  L_LEG_BTOF_EVENT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [2, 3, 1, 4],
    category: 'Signals',
  },
  L_ARM_SIGNAL: {
    maxValue: 100,
    scale: 1,
    alleleValues: [2, 2, 2, 1],
    category: 'Signals',
  },
  L_ARM_FTOB_REACT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [2, 1, 2, 3],
    category: 'Signals',
  },
  L_ARM_FTOB_EVENT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [3, 1, 2, 4],
    category: 'Signals',
  },
  L_ARM_BTOF_REACT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 2, 1, 3],
    category: 'Signals',
  },
  L_ARM_BTOF_EVENT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [2, 3, 1, 4],
    category: 'Signals',
  },
  L_TAIL_SIGNAL: {
    maxValue: 100,
    scale: 1,
    alleleValues: [3, 1, 2, 4],
    category: 'Signals',
  },
  L_TAIL_FTOB_REACT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 3, 2],
    category: 'Signals',
  },
  L_TAIL_FTOB_EVENT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 2, 3, 4],
    category: 'Signals',
  },
  L_TAIL_BTOF_REACT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 3, 2],
    category: 'Signals',
  },
  L_TAIL_BTOF_EVENT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [2, 1, 3, 4],
    category: 'Signals',
  },
  L_NECK_SIGNAL: {
    maxValue: 100,
    scale: 1,
    alleleValues: [4, 1, 2, 3],
    category: 'Signals',
  },
  L_NECK_FTOB_REACT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 4, 2],
    category: 'Signals',
  },
  L_NECK_FTOB_EVENT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [1, 2, 3, 4],
    category: 'Signals',
  },
  L_NECK_BTOF_REACT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [0, 1, 4, 2],
    category: 'Signals',
  },
  L_NECK_BTOF_EVENT: {
    maxValue: 100,
    scale: 1,
    alleleValues: [2, 1, 3, 4],
    category: 'Signals',
  },
} satisfies Record<string, GeneData>;

export type GeneNames = keyof typeof GENES;
export const isGeneName = (name: string): name is GeneNames => name in GENES;

export const HELIX_MAP: GeneNames[][] = [
  [
    'BONES',
    'BONES2',
    'OSTODERM',
    'OSTO_SIZE',
    'GIANT_DWARF',
    'TAIL_BOTTOM',
    'LEG_STRETCH2',
    'ARM_STRETCH2',
    'HEAD_THICK_SKULL',
    'NECK_STIFF',
  ],
  [
    'GUT',
    'GUT_IS_UDDER',
    'DERRIERE',
    'LEG_IS_CIRCLE',
    'FOOT_IS_CIRCLE',
    'TONGUE',
    'TONGUE_SEGS',
    'BELLY_ALT',
    'PAT_BELLY',
    'LITTER_SIZE',
    'OLD_AGE',
    'OMNIVORE',
    'LIMP',
  ],
  [
    'MUSCLE_USE',
    'TAIL_STIFF',
    'LEG_FLEXIBILITY',
    'LEG_FLEX_BIAS',
    'TAIL_FLEXIBILITY',
    'TAIL_SPEED',
    'LEG_AND_ARM_LIMP',
    'ARM_STRENGTH',
    'ARM_FLEXIBILITY',
    'ARM_FLEX_BIAS',
    'NECK_FLEXIBILITY',
    'NECK_FLEX_BIAS',
    'BRAIN_SPASTIC',
  ],
  [
    'SPLAY',
    'LEG_IN',
    'LEG_IN2',
    'TAIL_ANGLE',
    'TAIL_JOINT_TYPE',
    'LEG_JOINT_TYPE',
    'HAS_KNEE',
    'KNEE_MIN',
    'KNEE_MAX',
    'ARM_JOINT_TYPE',
    'HAS_ELBOW',
    'ELBOW_RANGE',
    'NECK_JOINT_TYPE',
    'HEAD_JOINTED',
    'STIFF_JOINTS',
  ],
  [
    'LEG_TAG',
    'LEG_HAS_FOOT',
    'LEG_COUNT',
    'LEG_THRUST_BACK',
    'ARM_TAG',
    'ARM_HAS_HAND',
    'NECK_TAG',
    'NECK_SLOUCH',
    'NECK_ONTOP',
    'BREAK_FORCE',
    'EAR_X',
  ],
  [
    'QUADRUPED',
    'BIPED',
    'UPARM_TAG',
    'UPARM_Y',
    'UPARM_GOOFY',
    'ARM_FORWARD',
    'UPARM_ANGLE',
    'WHITE_IS_LETHAL',
  ],
  [
    'ASPECT',
    'SKINNY',
    'CHEST_BIG',
    'CHEST_SMALL',
    'NECK_TYPE',
    'NECK_LENGTH',
    'NECK_GIRAFFE',
    'NECK_THICKNESS',
    'NECK_ANGLE',
    'NECK_COCK',
    'NECK_SIZE',
  ],
  [
    'TAIL_TAG',
    'TAIL_EXISTS',
    'TAIL_SIZE',
    'TAIL_SHORT',
    'TAIL_ASPECT',
    'TAIL_SHAPE',
    'TAIL_SEGMENTS',
    'TAIL_WAG',
  ],
  [
    'LEG_TYPE',
    'LEG_LENGTH',
    'LEG_STRETCH',
    'LEG_SKEW',
    'LEG_STRENGTH',
    'LEG_PENCIL',
    'ARM_TYPE',
    'ARM_LENGTH',
    'ARM_STRETCH',
    'ARM_SKEW',
    'ARM_NODE_SCALE',
  ],
  [
    'HAS_FOOT',
    'FOOT_SIZE',
    'FOOT_CLOWN',
    'FOOT_THICKNESS',
    'FOOT_TOE',
    'FOOT_BACKWARDS',
    'HAS_HAND',
    'HAND_WIDTH',
    'HAND_LENGTH',
    'HAND_FINGER',
    'SKIN_HANDS',
  ],
  [
    'HEAD_SIZE',
    'HEAD_X_GROWTH',
    'HEAD_Y_GROWTH',
    'HEAD_ASPECT',
    'HEAD_SQUARE',
    'HEAD_HAS_BACK',
    'HEAD_GIANT',
    'HEAD_SHRUNK',
    'HEAD_CHIMERA',
    'EYEBOX_X',
    'EYEBOX_Y',
    'EYEBOX_SIZE',
    'SKIN_HEAD',
  ],
  [
    'EYE_STYLE',
    'BUGEYE',
    'EYE_SIZE',
    'PUPIL_SIZE',
    'HAS_PUPIL',
    'BROW_SIZE',
    'BROW_SLANT',
    'EYE_HUE',
    'EAR_STYLE',
    'EAR_SHAPE',
    'EAR_SIZE',
    'EAR_ASPECT',
    'EAR_SLANT',
    'EAR_INTERIOR',
    'EAR_FLOP',
  ],
  [
    'TEETH_SHAPE',
    'HAS_MOUTH',
    'MOUTH_Y',
    'MOUTH_SIZE',
    'JAW',
    'TEETH_UPPER',
    'TEETH_UPPER2',
    'NOSE_STYLE',
    'NOSE_INNY',
    'NOSE_Y',
    'NOSE_SIZE',
    'NOSE_INTERIOR',
    'FLU_IMMUNITY',
  ],
  [
    'HAS_ANTLERS',
    'ANTLER_X',
    'ANTLER_W',
    'ANTLER_H',
    'ANTLER_TAPER',
    'ANTLER_POM',
    'ANTLER_COLOR',
    'POM_COLOR',
    'POM_USECOLOR',
    'HAT_POM',
    'HAT_POM_IS_LID',
  ],
  [
    'ANTLER_REC',
    'ANTLER_REC2',
    'ANTLER_FLIP',
    'ANTLER_MOD',
    'ANTLER_SCALEH',
    'ANTLER_SCALEW',
    'ANTLER_ANGLE',
    'ANTLER_ANGLE2',
    'ANTLER_ANGLE_RAND',
    'ANTLER_T1',
    'ANTLER_T2',
  ],
  [
    'HAT_EXISTS',
    'HAT_SIZE',
    'HAT_RAKE',
    'HAT_ASPECT',
    'HAT_TAPER',
    'HAT_CLONE',
    'HAT_BACK_SCALE',
    'HAT_FRONT_SCALE',
    'HAT_BACK_ANGLE',
    'HAT_FRONT_ANGLE',
    'HAT_ANGLE_RAND',
    'HAT_FLIP',
    'HAT_T',
  ],
  [
    'BASE_BROWN',
    'BASE_BLACK',
    'BASE_RED',
    'BASE_GREEN',
    'GREEN_KNOCKOUT',
    'BASE_CREAM',
    'ALT_BLUE',
    'SPOT_YELLOW',
    'SKIN_HUE',
    'SKIN_HUE2',
    'SWAP_BASE_SPOT',
    'SWAP_ALT_SPOT',
    'WHITE',
    'NOSE_HUE',
    'HOOF_COLOR',
  ],
  [
    'AGOUTI',
    'FOOT_IS_HOOF',
    'COON_EYE',
    'EAR_COMP',
    'TAIL_ALT',
    'PAT_SPLIT',
    'PAT_STRIPE',
    'PAT_SPOT',
    'PAT_PERLIN',
    'PAT_PERLIN2',
    'PAT_PERLIN_SIZE',
  ],
  [
    'NARCOLEPSY',
    'SPEED_FACTOR',
    'NECK_SPEED',
    'RAMPAGE',
    'SPINAL_LOCO',
    'HIGH_INTELLECT',
    'L_LEG_SIGNAL',
    'L_ARM_SIGNAL',
    'L_TAIL_SIGNAL',
    'L_NECK_SIGNAL',
    'LOCO_SYNC',
  ],
  [
    'L_LEG_FTOB_REACT',
    'L_LEG_FTOB_EVENT',
    'L_LEG_BTOF_REACT',
    'L_LEG_BTOF_EVENT',
    'L_ARM_FTOB_REACT',
    'L_ARM_FTOB_EVENT',
    'L_ARM_BTOF_REACT',
    'L_ARM_BTOF_EVENT',
    'L_TAIL_FTOB_REACT',
    'L_TAIL_FTOB_EVENT',
    'L_TAIL_BTOF_REACT',
    'L_TAIL_BTOF_EVENT',
    'L_NECK_FTOB_REACT',
    'L_NECK_FTOB_EVENT',
    'L_NECK_BTOF_REACT',
    'L_NECK_BTOF_EVENT',
  ],
];

export const GENE_LOC: Record<string, GeneLocation> = {};
HELIX_MAP.forEach((h, hi) =>
  h.forEach((g, pi) => {
    GENE_LOC[g] = { helixNumber: hi, position: pi };
  }),
);
export const ALL_CATS = [
  ...new Set(Object.values(GENES).map((g) => g.category)),
].sort();
